"""empty message

Revision ID: adf5ec3f1f2d
Revises: 3831035c7590
Create Date: 2024-10-21 19:03:31.662931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf5ec3f1f2d'
down_revision = '3831035c7590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
